server:
  port: 8881
spring:
  profiles:
    active: beta
  application:
    name: eureka-client-home

eureka:
  instance:
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    hostname: eureka-client-home
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka

feign:
  client:
    config:
      eureka-client-sku:
        readTimeout: 4000
        connectTimeout: 4000
        loggerLevel: FULL
