server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**
  datasource:
    username: admin
    password: 123456
    driver-class-name:mysql: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ape_frame?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: root
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
      wall:
        enabled: true

sql:
  beauty:
    show: true
    page: true
    fill: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
      #id类型。
      id-type: ASSIGN_ID # 默认为ASSIGN_ID
  type-aliases-package: com.airport.ape.user.entity.po


#logging:
#  config: classpath:log4j2.xml
logging:
  config:
    classpath: log4j2.xml
  level:
    com.airport.ape.user.mapper: debug

log:
  aop:
    enable: true

traceId:
  filter:
    enable: false

user:
  property:
    default:
      packaging: com.example
      groupId: airport.cargos.web
      artifactId: airport_cargos_web_example
      version: 1.0.0-SNAPSHOT
      application:
